// This file was generated by silverstripe/cow from javascript/lang/src/ar.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ar', {
    "CWP.SPECIFYALTTEXT": "%s ليس لها نص بديل وهو مطلوب للصور غير المزخرفة.\n\nهل أنت متأكد أنك تريد التحديث؟"
});
}