// This file was generated by silverstripe/cow from javascript/lang/src/eo.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "CWP.SPECIFYALTTEXT": "%s ne havas alt-tekston, kiu bezonatas por nedekoraciaj bildoj.\n\nĈu vi certas ke vi volas ĝisdatigi?"
});
}