// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/eo.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('eo', {
    "CWP.SPECIFYALTTEXT": "%s ne havas alt-tekston, kiu bezonatas por nedekoraciaj bildoj.\n\nĈu vi certas ke vi volas ĝisdatigi?"
});
}