// This file was generated by GenerateJavaScriptI18nTask from javascript/lang/src/fi.js.
// See https://github.com/silverstripe/silverstripe-buildtools for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('fi', {
    "CWP.SPECIFYALTTEXT": "Kohteella %s ei ole ALT-tekstiä, joka tulisi olla kaikilla ei kuvitukseksi tarkoitetuilla kuvilla.\n\nHaluatko varmasti päivittää?"
});
}