// This file was generated by silverstripe/tx-translator from javascript/lang/src/fi.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi', {
    "CWP.SPECIFYALTTEXT": "Kohteella %s ei ole ALT-tekstiä, joka tulisi olla kaikilla ei kuvitukseksi tarkoitetuilla kuvilla.\n\nHaluatko varmasti päivittää?"
});
}