// This file was generated by silverstripe/cow from javascript/lang/src/id.js.
// See https://github.com/tractorcow/cow for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('id', {
    "CWP.SPECIFYALTTEXT": "%s tidak ada teks alternatif yang diperlukan untuk gambar non-dekorasi.\n\nAnda yakin ingin memperbarui?"
});
}