// This file was generated by silverstripe/tx-translator from javascript/lang/src/id.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('id', {
    "CWP.SPECIFYALTTEXT": "%s tidak ada teks alternatif yang diperlukan untuk gambar non-dekorasi.\n\nAnda yakin ingin memperbarui?"
});
}