// This file was generated by silverstripe/cow from javascript/lang/src/ne.js.
// See https://github.com/tractorcow/cow for details
if(typeof(ss) == 'undefined' || typeof(ss.i18n) == 'undefined') {
	if(typeof(console) != 'undefined') console.error('Class ss.i18n not defined');
} else {
	ss.i18n.addDictionary('ne', {
    "CWP.SPECIFYALTTEXT": "%s has no alt text which is required for non-decorative images.\n\nAre you sure you want to update?"
});
}