// This file was generated by silverstripe/tx-translator from javascript/lang/src/ru.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ru', {
    "CWP.SPECIFYALTTEXT": "%s не содержит альтернативного текста, что нежелательно для не-служебных изображений.\n\nХотите продолжить?"
});
}