// This file was generated by silverstripe/tx-translator from javascript/lang/src/sr_RS.js.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sr_RS', {
    "CWP.SPECIFYALTTEXT": "%s has no alt text which is required for non-decorative images.\n\nAre you sure you want to update?"
});
}